# Generated by Django 3.2.23 on 2023-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='titanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(default=0)),
                ('Passenger_Class', models.CharField(max_length=30)),
                ('Starting_Point', models.CharField(max_length=15)),
                ('Siblings_Spouse', models.CharField(max_length=15)),
                ('Parents_Children', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=15)),
            ],
        ),
    ]
