# Generated by Django 3.2.23 on 2023-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Parents_Children',
            field=models.CharField(choices=[('Parents_Children', 'Parents_Children'), ('No_Parents_Children', 'No_Parents_Children')], max_length=30),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Passenger_Class',
            field=models.CharField(choices=[('First_Class', 'First_Class'), ('Second_Class', 'Second_Class'), ('Third_Class', 'Third_Class')], max_length=30),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Siblings_Spouse',
            field=models.CharField(choices=[('Siblings_Spouse', 'Siblings_Spouse'), ('No Siblings_Spouse', 'No Siblings_Spouse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Starting_Point',
            field=models.CharField(choices=[('S', 'S'), ('C', 'C'), ('Q', 'Q')], max_length=15),
        ),
    ]
