# Generated by Django 3.2.23 on 2023-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanicapi', '0002_auto_20231102_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Gender',
            field=models.CharField(choices=[('Male', '0'), ('Female', '1')], max_length=15),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Parents_Children',
            field=models.CharField(choices=[('Parents_Children', '1'), ('No_Parents_Children', '0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Passenger_Class',
            field=models.CharField(choices=[('First_Class', '1'), ('Second_Class', '2'), ('Third_Class', '3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Siblings_Spouse',
            field=models.CharField(choices=[('Siblings_Spouse', '1'), ('No Siblings_Spouse', '0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Starting_Point',
            field=models.CharField(choices=[('S', '0'), ('C', '1'), ('Q', '2')], max_length=15),
        ),
    ]
